walinejs/waline

- packages/client/src/i18n/zh-TW.js
- packages/server/src/service/notify.js
feat: 增加 MAIL_SUBJECT_ADMIN 和 MAIL_TEMPLATE_ADMIN 配置
improvement: 修改部分zh-tw 用詞
> feat: 增加 MAIL_SUBJECT_ADMIN 和 MAIL_TEMPLATE_ADMIN 配置

- packages/admin/src/App.js
- packages/admin/src/components/Header.js
- packages/admin/src/index.js
- packages/admin/src/pages/login/index.js
- packages/admin/src/pages/profile/index.js
- packages/admin/src/services/user.js
- packages/admin/src/store/user.js
- packages/client/src/components/CommentBox.js
- packages/server/src/controller/user.js
- packages/server/src/logic/base.js
- packages/server/src/logic/user.js
Add profile setting page then user can modify profile #107
> feat(admin): add profile setting page for dashboard and client

- docs/server/basic.md
> 增加对Akismet的描述

- docs/client/basic.md
> docs: update docs

- packages/client/src/components/CommentBox.js
fix https://github.com/lizheming/waline/issues/126
> fix(client): submit button text in comment box

- packages/server/Dockerfile
[node:8-alpine wrong timezone behavior #626](https://github.com/nodejs/docker-node/issues/626)
> fix(dockerfile): alpine timezone bug

- docs/en/server/vps-deploy.md
- docs/server/vps-deploy.md
关于 docker stack deploy 或者 docker-compose 的介绍
> doc: ... via docker stack deploy or docker-compose

- packages/hexo-next/default.yaml
resolves https://github.com/lizheming/waline/issues/145#issuecomment-765592433
> fix: comment hexo-next default config lang

- packages/hexo-next/index.js
Prefetching of waline server will improve the performance.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-DNS-Prefetch-Control
for reference.
> add dns-prefetch for the server

- packages/hexo-next/index.js
> Revert "add dns-prefetch for the server"

- .gitignore
- .vscode/settings.json
Sorry, I commit my vscode config files to this repo by mistake.
This PR will remove it.
BTW: The PR descriptioin will likely be included in default commit comment. Please remove these lines.
> refactor: remove vscode settings

- packages/client/__tests__/xss.spec.js
- packages/client/src/utils/mark.js
disable forms and inputs and force preload to be 'none'
> feat(client): improve comment parser

- .github/workflows/test.yml
use `yarn workspace` to prevent issue with npm@v6
> ci: fix broken workflow

- .gitignore
- docs/client/avatar.md
- docs/client/basic.md
- docs/en/client/avatar.md
- docs/en/client/basic.md
- packages/admin/src/pages/manage-comments/utils.js
- packages/admin/src/pages/profile/index.js
- packages/client/src/utils/default.js
> 修复中国内地无法显示用户头像的问题

- packages/client/build/webpack.common.js
- packages/client/build/webpack.config.js
- packages/client/build/webpack.noStyle.js
- packages/client/src/components/CommentBox.vue
- packages/client/src/utils/markdown.ts
> Revert "feat(client): splilt markdown to a chunk"

- packages/admin/src/style/custom.scss
- packages/admin/src/style/style.css
> 修复评论管理后台表情包过大的问题

- docs/advanced/ecosystem.md
- docs/en/advanced/ecosystem.md
Mister-Hope，不好意思哈，我刚刚才看到您在AprilComment文档下的留言（因为文档站点没有开启回复提醒）
我已经在ecosystem中添加了AprilComment的简单介绍，不知道这样子写，格式行不行哈😉
> 添加三方客户端实现AprilComment的简单介绍

- package-lock.json
- packages/client/package.json
> Revert "build(deps-dev): bump @vue/compiler-sfc from 3.1.5 to 3.2.1"

- README.md
- README_CN.md
- docs/advanced/ecosystem.md
- docs/advanced/intro.md
- docs/en/advanced/ecosystem.md
- docs/en/advanced/intro.md
The links associated with AprilComment need to be updated bacause I renamed my username of Github account.
> update links associated with third-party client AprilComment

- packages/server/src/config/config.js
- packages/server/src/controller/comment.js
- packages/server/src/controller/token.js
- packages/server/src/logic/base.js
> Revert "feat: use Libravatar in admin panel"

- docs/en/reference/server.md
- docs/reference/server.md
docs: 刪除多餘的空行,會導致無法識別 nunjucks 語法
> docs: 刪除多餘的空行,會導致無法識別 nunjucks 語法

- .github/workflows/docker-release.yml
没做测试，不确定 `docker/build-push-action@v2` 包能否推 ghcr.io，不过应该没问题
> ci(docker-release.yml): docker push ghcr.io

- packages/server/src/controller/comment.js
Save comment markdown content rather than html content before, and render markdown when output comment data.
relate issue https://github.com/walinejs/waline/issues/552#issuecomment-957176188
> [FEAT] Save Comment Markdown content

- packages/client/src/Waline.vue
- packages/client/src/composables/userInfo.ts
- packages/client/src/utils/comment.ts
- packages/client/src/utils/fetch.ts
- packages/client/src/widget/recentComments.ts
- packages/server/src/controller/comment.js
- packages/server/src/logic/base.js
- packages/server/src/service/storage/cloudbase.js
- packages/server/src/service/storage/github.js
- packages/server/src/service/storage/inspirecloud.js
- packages/server/src/service/storage/leancloud.js
- packages/server/src/service/storage/mongodb.js
output login user's comment if the comment is waiting audit or it's spam.
> [FEAT] comment list add login user support

- README.md
- README_CN.md
- docs/src/advanced/ecosystem.md
- docs/src/advanced/intro.md
- docs/src/en/advanced/ecosystem.md
- docs/src/en/advanced/intro.md
我是客户端实现AprilComment的作者，因为工作的原因，没法继续提供AprilComment项目的维护，导致项目有些年久失修了，有些新特性我也没法跟进，因为太忙了，并没有过多的空闲时间来维护开源项目。
现在也留下了许多小问题，小bug。只好发起PR暂时移除项目的链接，避免后面的人踩坑。如果以后还有机会再见的话，我会重写一个功能更加完善的项目。
最后感谢各位作者大佬在这些日子里给与AprilComment项目的支持，谢谢！
> 移除客户端实现项目AprilComment的链接

- packages/admin/src/App.js
- packages/admin/src/components/Header.js
- packages/admin/src/locales/en.json
- packages/admin/src/locales/zh-CN.json
- packages/admin/src/locales/zh-TW.json
- packages/admin/src/pages/migration/index.js
- packages/admin/src/utils/download.js
- packages/server/src/controller/db.js
- packages/server/src/logic/base.js
- packages/server/src/logic/db.js
> [FEAT] add import and export for waline

- packages/admin/src/locales/en.json
- packages/admin/src/locales/zh-CN.json
- packages/admin/src/locales/zh-TW.json
- packages/admin/src/pages/profile/index.js
- packages/server/src/controller/user.js
> [FEAT] add change avatar support

- packages/admin/src/App.js
- packages/admin/src/locales/en.json
- packages/admin/src/locales/zh-CN.json
- packages/admin/src/locales/zh-TW.json
- packages/admin/src/pages/forgot/index.js
- packages/admin/src/pages/login/index.js
- packages/admin/src/services/auth.js
- packages/admin/src/store/user.js
- packages/server/src/controller/user/password.js
- packages/server/src/logic/user/password.js
> [FEAT] add forgot password support

- packages/admin/src/pages/profile/twoFactorAuth.js
> chore: free 2fa apps

- docs/src/reference/server.md
> doc: fix server env table

- packages/server/src/extend/think.js
- packages/server/src/service/storage/leancloud.js
LeanCloud has no native group by support, we use many fetch to polyfill it. we make a cache to optimize the polyfill performance.
> [chore] add group count cache for leancloud

- packages/client/src/components/CommentCard.vue
- packages/client/src/components/Waline.vue
- packages/client/src/composables/userInfo.ts
- packages/client/src/typings/comment.ts
- packages/client/src/utils/fetch.ts
- packages/server/src/controller/comment.js
> Revert "WIP: [FEAT] Add comment manage action at client"

- docs/src/en/guide/server/databases.md
- docs/src/guide/server/databases.md
- packages/server/src/config/adapter.js
- packages/server/src/extend/think.js
修改如下
- 允许使用SSL连接到PostgreSQL和MySQL
- 暂时解决了获取IPv6地址的地区时报错的问题(现在会返回空字符串)
> 允许使用SSL连接到PostgreSQL和MySQL

- docs/src/.vuepress/sidebar.ts
> Fix a typo

- docs/src/guide/client/emoji.md
> Revert "Update and rename docs/src/guide/client/emoji.md to 文档/源代码/指导/客户/emoj…"

- packages/client/__tests__/highlighter.html
- packages/client/__tests__/init.html
- packages/client/__tests__/katex.html
- packages/client/__tests__/legacy.html
- packages/client/__tests__/mathjax.html
- packages/client/__tests__/pageview.html
- packages/client/src/components/CommentCard.vue
- packages/client/src/styles/card.scss
- packages/client/template/init.html
- packages/client/template/legacy.html
- packages/client/template/pageview.html
增加以下 CSS
```css
.wl-card .wl-meta > span::before {
content: '';
width: 1em;
height: 1em;
display: inline-block;
background-repeat: no-repeat;
background-position: center center;
margin-right: 2px;
}
.wl-card .wl-meta > .wl-addr::before {
background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="rgb(153,153,153)"><path d="M444.52 3.52L28.74 195.42c-47.97 22.39-31.98 92.75 19.19 92.75h175.91v175.91c0 51.17 70.36 67.17 92.75 19.19l191.9-415.78c15.99-38.39-25.59-79.97-63.97-63.97z"></path></svg>');
}
.wl-card .wl-meta > .wl-os::before,
.wl-card .wl-meta > .wl-browser::before {
background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="rgb(153,153,153)"><path d="M464 32H48C21.5 32 0 …
```
> feat(client): rebuild comment meta, close #1316 #1351

- packages/server/src/service/storage/mysql.js
> fix: fix #1357

- docs/src/advanced/ecosystem.md
Hugo theme FixIt supported waline client
> Docs: Hugo theme FixIt supported waline client

- docs/src/guide/get-started.md
> Add Chinese video tutorial

- packages/admin/src/components/Header.js
- packages/admin/src/locales/en.json
- packages/admin/src/locales/zh-CN.json
- packages/admin/src/locales/zh-TW.json
- packages/admin/src/store/user.js
- packages/admin/src/style/custom.scss
- packages/admin/src/utils/request.js
- packages/server/package.json
- pnpm-lock.yaml
> [FEAT] add new version tips 

- docs/src/en/guide/server/notification.md
Was setting up my email notifications using Mailjet and came across some issues, where the documentation could have been more clear.
> Add email notification defaults, templates to docs

- docs/src/en/guide/client/widget/README.md
- docs/src/en/guide/client/widget/recent-comment.md
- docs/src/en/guide/client/widget/user-list.md
- docs/src/guide/client/widget/README.md
- docs/src/guide/client/widget/user-list.md
- packages/client/src/api/index.ts
- packages/client/src/api/user.ts
- packages/client/src/styles/index.scss
- packages/client/src/styles/userlist.scss
- packages/client/src/widgets/index.ts
- packages/client/src/widgets/userList.ts
- packages/server/src/controller/user.js
- packages/server/src/logic/user.js
- packages/server/src/service/storage/leancloud.js
```js
Waline.UserList({
el: '#comment-user',
serverURL: 'http://waline.vercel.app',
count: 10,
mode: 'list', // mode: 'wall'
});
```
| mode=list | mode=wall |
|--|--|
| ![image](https://user-images.githubusercontent.com/424491/194545548-5ee2a523-8653-4e8b-b19e-93e26be2f15b.png) | ![image](https://user-images.githubusercontent.com/424491/194546121-9967b746-af74-4029-8bde-dbd9fc2376e3.png) |
> [FEAT] Add user list widget for waline

- docs/src/advanced/intro.md
- docs/src/en/advanced/intro.md
> docs: fix the cloudbase url

- packages/server/package.json
- packages/server/src/service/storage/mongodb.js
- pnpm-lock.yaml
> fix: fix #1510

- docs/src/en/guide/server/notification.md
- docs/src/guide/server/notification.md
- packages/server/src/config/config.js
- packages/server/src/service/notify.js
> Add Feishu/Lark Notification

- packages/server/src/extend/controller.js
- packages/server/src/service/notify.js
> fix: fix #1524

- docs/src/guide/server/railway.md
原先的模板链接railway已经不再支持, 因此按照旧模板的内容创建了一个可用的新模板
> 修改模板链接为新模板

- docs/src/advanced/ecosystem.md
- docs/src/en/advanced/ecosystem.md
add hexo theme support from freemind.bithack
> docs: update ecosystem

- packages/client/src/api/comment.ts
- packages/client/src/components/WalineComment.vue
修改评论内容的时候多包了一层 comment 字段 https://github.com/walinejs/waline/blob/main/packages/client/src/components/CommentBox.vue#L557 ，这里统一了下都包上 comment 字段。
> fix: fix #1638 

- docs/src/advanced/ecosystem.md
- docs/src/en/advanced/ecosystem.md
新增 [Redefine](https://github.com/EvanNotFound/hexo-theme-redefine) 主题
> Add hexo-theme-redefine to the list

- docs/src/en/reference/server/env.md
- docs/src/reference/server/env.md
- packages/server/src/extend/think.js
optimize ip query logic for bad case `15.204.56.1` from #1718.
> fix: fix #1718

- packages/client/package.json
- packages/client/src/components/CommentBox.vue
- packages/client/src/utils/userAgent.ts
- pnpm-lock.yaml
> feat: add Windows 11 agent support

- docs/src/cookbook/customize/database.md
- docs/src/cookbook/customize/userdb.md
- docs/src/en/cookbook/customize/database.md
- docs/src/en/cookbook/customize/userdb.md
- docs/src/en/reference/server/config.md
- docs/src/reference/server/config.md
- packages/server/src/controller/article.js
- packages/server/src/controller/comment.js
- packages/server/src/controller/db.js
- packages/server/src/controller/oauth.js
- packages/server/src/controller/token.js
- packages/server/src/controller/token/2fa.js
- packages/server/src/controller/user.js
- packages/server/src/controller/user/password.js
- packages/server/src/controller/verification.js
- packages/server/src/extend/controller.js
- packages/server/src/logic/base.js
- packages/server/src/logic/comment.js
```typescript
type strNum = string | number;
type UserFields = 'objectId' | 'display_name' | 'email' | 'password' | 'type' | 'label' | 'url' | 'avatar' | 'github' | 'twitter' | 'facebook' | 'google' | 'weibo' | 'qq' | '2fa' | 'createdAt' | 'updatedAt';
type UserData = Record<UserFields, strNum>;
type UsersWhere = Record<UserFields, strNum | ['IN', strNum[]]>;
interface UsersOptions {
field: string[];
desc?: UserFields;
limit?: number;
offset?: number;
}
interface UsersModel {
select: (where: UsersWhere, options: UsersOptions) => UserData[];
add: (user: Partial<UserData>) => UserData;
update: (user: Partial<UserData>, where: UsersWhere) => UserData;
delete: (where: UsersWhere) => void;
count: (where: UsersWhere) => number;
}
function model(modelName): UsersModel | undefined {
if (modelName …
```
> [FEAT] custom model

- docs/src/guide/features/emoji.md
> 再次重新修改版本号并展示元气骑士表情的链接

- packages/server/src/controller/comment.js
这条评论的点赞量都被别有用心之人搞成什么样了😅：
---
What kind of likes have been made to this comment by people with ulterior motives 😅:
> feat: 禁止点赞小于0 || feat: No likes less than 0

- README.md
- docs/src/en/guide/features/notification.md
- docs/src/guide/features/notification.md
- packages/server/src/service/notify.js
Support qmsg privatization service about QQ notification.
For more content, please refer to QMSG official website: [Docker Privatization article](https://qmsgpvt.zendee.cn/docs/plus/#%E7%A7%81%E6%9C%89%E4%BA%91%E9%83%A8%E7%BD%B2%E8%A6%81%E6%B1%82)
> update: about QQ notification

- docs/src/guide/features/notification.md
- docs/src/reference/server/config.md
- packages/server/src/config/config.js
- packages/server/src/service/notify.js
新增Server酱通知模版
---
Add ServerChan Notification Template
> chore: update notify, add ServerChan Notification Template

- docs/src/guide/get-started/server.md
zh-CN locale use `、` for listing multiple items
> fix(docs): minor punctuation optimize

- packages/server/src/service/avatar.js
implement SHA256 filter for GRAVATAR_STR #2487
> feat(server): add SHA256 filter for GRAVATAR_STR

- docs/src/advanced/ecosystem.md
- docs/src/en/advanced/ecosystem.md
Add gatsby-plugin-waline to ecosystem.md.
> docs: add gatsby-plugin-waline to ecosystem.md

- docs/src/en/reference/server/plugin.md
- docs/src/reference/server/plugin.md
https://github.com/zhullyb/waline-plugin-llm-reviewer/
A new waline plugin, use large language model to review comments.
> docs: add waline-plugin-llm-reviewer

- docs/src/en/guide/database.md
- docs/src/guide/database.md
PlanetScale and FreeDB have changed plan recently, and the information needs to be updated
> [Docs]: Update information about PlanetScale and FreeDB

- packages/server/Dockerfile.source-build-alpine
Added building server side docker image from source code.
添加了从源代码构建服务器端 docker 镜像。
> chore: Added building server side docker image from source code.

- eslint.config.js
- package.json
- packages/client/src/components/CommentBox.vue
Close: #3043.
TLDR. `isDef(null) == true`
And fix ESLint related error.
And add missing `onlyBuiltDependencies` field cuz https://github.com/pnpm/pnpm/releases/tag/v10.0.0.
> fix(client): image uploader config and misc
