walinejs/waline

example/vercel.json

原来访问http://{{serverURL}}/ui 会出现404错误

Fix vercel deployment 404 error

---

packages/hexo-next/README.md
packages/hexo-next/default.yaml
packages/hexo-next/index.js

Fix the bug in hexo-next-waline plugin that not showing comment_count in postMeta.

fix(hexo/next): show comment_count in postMeta

---

docs/en/server/notification.md
docs/server/notification.md
packages/server/src/service/notify.js

实现了 Telegram 机器人的评论通知功能，文档那边也相应修改了。
不过实现的过程个人感觉十分简陋。评论通知这里读取的变量 `{{self.comment | safe}}` 已经被渲染成 HTML 了，如果直接发送该段内容，Telegram 有可能不会接受而报错，因为其[只支持部分 HTML 标签](https://core.telegram.org/bots/api#html-style)。
Telegram 机器人是可以接受 [MarkDown 内容](https://core.telegram.org/bots/api#markdownv2-style) 的，所以我这里干脆把发送消息的内容写成了 MarkDown，然而因为变量 `{{self.comment | safe}}` 依然是 HTML，我这里只能做了一点简单的处理：把 `<p>`、换行符、表情这几个剔除，然后让评论内容变成代码格式。这样发送消息时候就不会报错，消息内容也会简洁一些。
当然最好的方式是，直接把用户在评论框中的 MarkDown 评论传递给 Telegram 机器人，这样就不会出现上面这样评论经过了 MarkDown-HTML-MarkDown 几个阶段转换的过程了。技术有限，我是搞不定了😂😂 如果可以的话可以进一步改进～
评论通知效果如下：

feat(vercel): Telegram notification support

---

packages/server/src/controller/index.js
packages/server/src/service/notify.js

- 看了一下 Telegram 通知的文档，感觉其实对 MarkDown 语法也限制很多，不经过特别处理很容易报错。干脆直接把评论内容的 MarkDown 源代码以代码格式都发送出去好了（为了通知内容简洁考虑，删除表情包的内容），现在这样起码不至于因为某些奇奇怪怪的格式而报错。
- 评论管理首页没法访问了，应该是不能正确读取 serverUrl 导致的，已修复。

fix(vercel): fix Telegram notify bug & comment admin index error

---

packages/server/src/service/notify.js

- 之前同时开启 QQ 和 Telegram 通知时候，专门为 Telegram 设置的评论内容会被覆盖，所以各自给了变量名。
- 此外调整了布局，减少了通知内容出现的空行，更为美观了。
- Telegram 通知内容中显示评论内部链接的内容是中文且不在变量里，都进行了如下修改：链接 -> Link ，或许可以便于以后实现通知内容的国际化（逃

fix(vercel): QQ and Tg notification layout

---

packages/admin/src/pages/manage-comments/index.js
packages/server/src/controller/comment.js
packages/server/src/service/notify.js

feat(vercel): add COMMENT_AUDIT env to audit comment before approved

---

docs/server/notification.md

更正SMTP_PASS描述

---

assets/waline.pgsql
assets/waline.sql
packages/admin/src/store/user.js
packages/client/src/components/CommentBox.js
packages/client/src/context.js
packages/client/src/i18n/en.js
packages/client/src/i18n/jp.js
packages/client/src/i18n/zh-CN.js
packages/client/src/i18n/zh-TW.js
packages/client/src/index.css
packages/client/src/utils/fetch.js
packages/server/src/controller/comment.js
packages/server/src/controller/token.js

1. Add login buttion in `@vercel/client`,  it will open a new window to load login url when you click.
2. The login page is same with admin dashboard. The login window will be closed after login success, also user info will passed to original page.
3. The original page will show user info in the page after received user info. All info input box will be hidden at the same time.
4. Then you can post your comment just input your comment text.
5. We can get user id by the login token at the backed, and we will add a new filed `user_id` to storage it.
---
1. 客户端增加登录按钮，点击登录按钮后会开启登录的新窗口。
2. 登录窗口复用了后台的登录，登录完成后会关闭当前窗口，并将用户信息传递给原页面。
3. 原页面获取到用户信息后展示，同时隐藏需要输入用户信息的输入框。
4. 此时输入评论内容即可直接发送了
5. 后台会通过登录密钥获取到用户 ID，并在数据中新增了 `user_id` 的关联字段。

feat: add client login support

---

packages/tcb-starter/cloudbaserc.json

一键部署下来发现应用名称是 ThinkJS，还是改成Waline好区分一点

把在TCB部署的名称改成Waline

---

packages/server/src/service/notify.js

在fork的仓库部署后更改不会生效，所以修改后就直接pr了，请公子看看这样是否可行。
更改有：1.去除评论内容的转义；2.去除多余的空行，使推送文本更紧凑和高效。

delete space in contentQQ

---

packages/server/Dockerfile

the pull  #137 did not fix the timezone
Timezone setting is now handled by [Setup-alpine#setup-timezone](https://wiki.alpinelinux.org/wiki/Alpine_setup_scripts#setup-timezone)

fix(Dockerfile): use alpine-conf

---

.github/workflows/docker-release.yml
.github/workflows/docker-test.yml
packages/server/Dockerfile.alpine
packages/server/docker-compose.yml

> 是否可以参考 [docker-waline](https://github.com/uuznn/docker-waline) 的构建方法。或者能否把仓库 [docker-waline](https://github.com/uuznn/docker-waline) 合并到 [walinejs](https://github.com/walinejs) 
⚠  需要在 `secrets` 填写  ⚠
- DOCKERHUB_USERNAME 
- DOCKERHUB_TOKEN 
支持的架构：
- linux/amd64
- linux/arm64
- linux/arm/v7
支持的Docker容器：
- debian( latest )
- alpine
---
⚠ 需要停止使用 Docker Hub的构建。因为Docker Hub会对本仓库的每一次commit构建新版本，是完全没有必要的。
因此只对 `packages/server/*` 触发构建
---
- 两个文件区分了 debian 和 alpine 的构建版本
- 取消使用仓库文件构建，转而使用 npm install 进行安装。⚠
- 因此 docker 版本会比推送到仓库时有一个版本的间隔。相比直接推送到 DockerHub 可以有一个冷静期
- 可以额外触发一次 workflow ci 推送最新版到 docker hub
- 添加了 docker compose 模板

使用 GitHub Actions 构建docker镜像

---

packages/client/__tests__/math.spec.ts
packages/client/src/utils/markdown.ts

修复以下问题：
1. 行内公式无法识别 `$\sqrt{x}$` 等以符号开头 和结尾的内容。
2. 连续的两个行间公式必须空出三行以 `'$$\n\n\n\n$$'` 为间隔，无法空一行以 `'$$\n\n$$'` 为间隔。
3. 当 `2` 发生时如 `‘$$y$$’` 等里面的 `'$y$'` 会被识别为行内公式。
4. 行间公式内无法换行。
此修改会引入一个新的行为：
* `'\n$$'` 和 `'$$\n'` 间的所有字符将被视为 tex

fix(client): fix math match

---

packages/client/src/styles/card.scss

修改前
修改后
并且移除了padding-left: 1em;

修复子评论回复按钮与父评论回复按钮不对齐bug

---

docs/en/guide/client/avatar.md
docs/en/reference/client.md
docs/guide/client/avatar.md
docs/guide/client/intro.md
docs/reference/client.md
packages/admin/src/pages/profile/index.js
packages/client/src/config/default.ts
packages/client/src/config/options.ts

Libravatar is a free, open-source avatar provider features federated hosting and Gravatar-compatible APIs. It also redirects to Gravatar automatically when no matching avatar exists in Libravatar.

feat: Use Libravatar as default avatar (profile picture) provider

---

packages/server/src/config/config.js
packages/server/src/controller/comment.js
packages/server/src/controller/token.js
packages/server/src/logic/base.js

This also changes the variable name from `avatarProxy` to `avatarProvider`.

feat: use Libravatar in admin panel

---

packages/admin/src/App.js

When Waline is served from a sub-directory, login redirection does not handle base URL and gives incorrect redirection:
> ${SITE_URL}/waline => ${SITE_URL}/waline/ui => ${SITE_URL}/ui/login/?redirect=/waline/ui/
This PR should concat the correct path and fix the issue, but more tests could be used. Some other redirection should also be reviewed.

fix: incorrect login redirection when served from subdirectory

---

packages/admin/src/App.js

Starting from 37fd504e6d1d8b18b0f557167626327204ceb52e, redirection will handle paths with subdirectories but lacks a leading slash:
> ${SITE_URL}/waline/ui => ${SITE_URL}/walineui/login/?redirect=/waline/ui/

fix: redirection URL lacks leading '/' when served from subdirectory

---

packages/server/src/service/notify.js

发送带有链接的消息会被 Qmsg 后台判定为「消息违规：恶意推广」而遭到拦截。据作者介绍「消息内容禁止带url链接」，具体情况见该页评论区：https://zendee.cn/archives/qmsg.html
故删去以下两个部分的代码：
- 提取消息中的链接
- 指向评论所在页面的链接

Delete URL links in Qmsg notification

---

packages/server/src/service/storage/mongodb.js

照mysql的写法修改了一下，在docker里测试有效
instance.limit(offset || 0, limit);

三方数据库为mongodb时count无效

---

docs/en/guide/client/avatar.md
docs/en/reference/client.md
docs/en/reference/server.md
docs/guide/client/avatar.md
docs/reference/client.md
docs/reference/server.md
packages/admin/src/pages/manage-comments/index.js
packages/admin/src/pages/manage-comments/utils.js
packages/server/src/config/config.js
packages/server/src/controller/comment.js
packages/server/src/logic/base.js

[FEATURE] Uniform avatar configure by AVATAR_PROXY

---

packages/client/src/styles/card.scss
packages/client/src/styles/panel.scss

如下图所示
虽然不会有人这么做，但这的确是个bug
> word-break
> 如果行末端有个英文单词如 **waline**，但是只剩下容纳两个字母的空间
> &nbsp;&nbsp; break-word: 它会直接跳到下一行显示完整的单词**waline**
> &nbsp;&nbsp; break-all: 它会被截断。第一行末端**wa** ，第二行开头 **line**

fix: 🐛[bug] Comment length out of the preview box

---

packages/client/src/components/CommentBox.vue

Email address is very complicated, maybe a simple regexp can't test all legal email. Maybe we can remove it at first.

[FEAT] remove email check regexp

---

docs/guide/server/aliyun-fc.md

The node-gyp is one of the dependencies of @serverless-devs/s . According to <https://github.com/nodejs/node-gyp#on-windows>, the operation of node-gyp under Windows requires Visual Studio C++ . In order to avoid users' doubts about errors and to avoid wasting time, a dependency notice for VC++ and a brief installation tutorial have been added.
Also, node-gyp requires Python on any platform, so a hint for Python dependencies has also been added.

doc: Add hints for dependencies on VC++ and Python

---

docs/reference/server.md

Added description for `avatarUrl` hook, which can rewrite the link of avatar.

doc: add description for `avatarUrl` hook

---

packages/server/src/config/adapter.js

fix issue #831: 对于MONGO_REPLICASET和MONGO_AUTHSOURCE两个选填的环境变量，当没有填写时，不会放入config/adapter.js的mongoOpt内。

---

packages/admin/src/store/user.js

- 如果在评论页面，勾选自动登录，并点击登录，是可以被正确记住的。
- 但如果在管理页面，勾选自动登录，并进行了登录。此时，在评论页面，点击登录按钮，弹窗后，会自动完成登录，但没有将remember属性带过来。这就导致，每次重新打开评论页面，都需要重新点一下登录。

fix: 修复客户端无法记住登录问题

---

package-lock.json
packages/server/package.json

`think-model-postgresql@1.1.7` has add case sensitive feature which waline have not compat for it, so we should lock version for it.

fix: fix #884

---

packages/admin/src/pages/manage-comments/index.js

修改了一下评论管理界面“作者”标签的位置

---

docs/guide/server/notification.md
docs/reference/server.md

加入对自定义后台JS加载脚本的描述。
由于在Vercel使用文档中的TG_TEMPLATE报错，故与代码内同步默认TG_TEMPLATE。

docs: WALINE_ADMIN_MODULE_ASSET_URL

---

assets/waline.sql
packages/admin/src/pages/manage-comments/index.js

修复置顶的问题，修改mysql表结构中sticky的类型为boolean

fix: sticky value error in mysql

---

.github/workflows/docs-deploy.yml
.github/workflows/test.yml
package.json
pnpm-lock.yaml

- use `packageManager` for pnpm
- i think we just need `lts/16` to test, because the node version has no effect on the user.
- use `--frozen-lockfile` to ensure version & use cache

ci: use packageManager for pnpm

---

packages/client/src/components/Waline.vue

fix: fix search option

---

packages/server/src/service/storage/mysql.js

修复 #1272 
问题出在think-model-abstract的parseData函数 [ref](https://github.com/thinkjs/think-model-abstract/blob/adb8ceb7a47aa6efc666b855e1a161a0f1f3f2dd/lib/schema.js#L56)
对于 `createdAt` 和 `updatedAt`，执行到此处时 `schema[key].default` 值为string类型的 `datetime('now', 'localtime')`，后续isFunction判断为假然后插入的时候就是`datetime('now', 'localtime')`而不是预期的时间了。
完全修起来比较麻烦要改think-model-abstract实现sqlite内置函数，可能会影响到thinkjs框架。这里取了个巧手动赋值一下日期。
修复前
修复后

fix: fix sqlite date field

---

docs/src/reference/env.md

页面内想要找到相关登陆的线索, 直觉上可能是搜索相应的供应商的名称而非一下就是oath

丰富OAUTH_URL的说明

---

docs/src/guide/server/notification.md

The misspelling of words only appears in Chinese docs, and English docs is not affected.

update docs misspelling of words

---

packages/client/src/comment.ts
packages/client/src/config/default.ts
packages/client/src/config/i18n/index.ts
packages/client/src/pageview.ts
packages/client/src/typings/waline.ts
packages/client/src/utils/config.ts
packages/client/src/widgets/recentComments.ts
packages/client/src/widgets/userList.ts
packages/client/template/icon.html
packages/client/template/init.html
packages/client/template/legacy.html

- use `navigator.language` as default lang option value 
- switch to `en-US` as default language

[FEAT] Default language switch

---

packages/client/src/styles/card.scss

最近将 valine 升级到 waline，在适配样式的时候，发现了 2 个小问题：
- 第一个问题：在回复评论的时候，昵称输入框会存在 margin-inline-end: 0.5em; 的属性，这个是由于与评论列表中的昵称样式匹配到了的原因，PS：昵称内容加粗也是，如果你们故意的当我没说。
- 第二个问题：在页面显示的最后一条评论有回复内容的时候，回复的评论内容下面的 border-bottom 会消失，无论它是不是最后一条。

fix(client): fix style issues

---

docs/src/reference/server/env.md

在服务端配置环境变量的时候，Vercel 可以正常启动 Waline 服务端，但是在测试评论的时候有问题。
问题详情：页面获取评论的时候出错，评论的时候页面提示 `path missing )` ，在 LeanCloud 中查看发现评论数据已经存储。
问题原因：经过排查 Waline 服务端的环境变量，发现由于配置安全域名 `SECURE_DOMAINS` 时，添加了传输协议的原因。
因此我修改了文档，补充了这一点。

docs: update docs

---

packages/client/src/components/CommentCard.vue

见 [discussions/1863](https://github.com/orgs/walinejs/discussions/1863)，目前只有评论正文里的网址才有 nofollow，而且该提问者指的也是昵称处的网址，故完善。

为昵称处的网址加上nofollow

---

docs/src/cookbook/README.md
docs/src/cookbook/customize/tex-renderer.md
docs/src/en/cookbook/README.md
docs/src/en/cookbook/customize/tex-renderer.md
docs/src/en/reference/client/props.md
docs/src/guide/features/syntax.md
docs/src/reference/client/props.md
docs/src/reference/server/env.md
packages/client/__tests__/markedMathExtension.spec.ts
packages/client/src/compact/v1.ts
packages/client/src/config/default.ts
packages/client/src/typings/base.ts
packages/client/src/typings/waline.ts
packages/client/src/utils/config.ts
packages/client/src/utils/markdown.ts
packages/client/src/utils/markedMathExtension.ts
packages/server/src/service/markdown/katex.js
packages/server/src/service/markdown/mathCommon.js
packages/server/src/service/markdown/mathjax.js

> TeX这个词的标准发音为/tɛx/，其中/x/相当于中文里“赫”字的[声母](https://zh.wikipedia.org/wiki/%E5%A3%B0%E6%AF%8D)，或者[苏格兰语](https://zh.wikipedia.org/wiki/%E4%BD%8E%E5%9C%B0%E8%98%87%E6%A0%BC%E8%98%AD%E8%AA%9E)“loch”一词中“ch”的发音（X其实是[希腊字母](https://zh.wikipedia.org/wiki/%E5%B8%8C%E8%85%8A%E5%AD%97%E6%AF%8D) χ）。发音接近“泰赫”。在[英语](https://zh.wikipedia.org/wiki/%E8%8B%B1%E8%AF%AD)和[法语](https://zh.wikipedia.org/wiki/%E6%B3%95%E8%AF%AD)中实际通常读作/tɛk/，发音接近“泰克”。TeX这个词来自[希腊文](https://zh.wikipedia.org/wiki/%E5%B8%8C%E8%85%8A%E6%96%87)中的 τέχνη （TEXNH），希腊文意为“艺术”和“制造”，也是英语中 technical（技术）的词源。书写时，三个字母都是大写，字母E应当低于其他两个字母。**而不支持下标的系统则只能这样书写：“TeX”。**（[维基百科](https://zh.wikipedia.org/wiki/TeX#%E5%8F%91%E9%9F%B3%E5%92%8C%E6%8B%BC%E5%86%99)）
根据上述规范，我将项目中的 Tex/TEX 替换为了 TeX。tex 保留的原因是为符合文件名等命名规范而可以做出妥协，但 Tex/TEX 实在不具有美感，因此进行了替换。
我比较担心的是这个 PR …

修复：将 Tex/TEX 转为 TeX || Fix: Convert Tex/TEX to TeX

---

packages/client/package.json
packages/client/rollup.config.mjs

When I use `@waline/client` in my project, it comes the "Could not find a declaration file or module '@waline/client/component'." error.
Looking into the `client` package of `waline`, I found there was a `TODO` mark and was lack of dts configuration for `component.ts`.
Running the build command, I found it saying rollup plugin is required.
After putting `@vitejs/plugin-vue` and `rollup-plugin-ts` before `rollup-plugin-dts`, it works!! 🎉
I added the `component.d.ts` file in the `node_modules` of my project, modified the `package.json` and the error disappeared.

chore(client): add component declaration rollup config

---

packages/server/src/service/storage/leancloud.js

在 https://github.com/walinejs/waline/commit/ba4a5147b31e8c9edc3295922cf270ae5e0494c1 引入的代码为每个浏览量更新的数据显式加入了updatedAt属性, 以修复 https://github.com/walinejs/waline/issues/1886 中提到的MySQL的updatedAt字段不会自动更新的问题.
然而, 使用leancloud作为存储时, 会因为updatedAt字段被作为leancloud保留字段导致api调用出错. 这一属性leancloud会自动填充, 不能显式指定.
我在leancloud存储对象update时删除了updatedAt属性以修复这一问题, 并且不会影响其他存储服务正常工作.
---
The code introduced at https://github.com/walinejs/waline/commit/ba4a5147b31e8c9edc3295922cf270ae5e0494c1 explicitly adds the updatedAt attribute to the data updated for each page view to fix https://github.com/walinejs/waline/issues/ The problem mentioned in 1886 is that MySQL's updatedAt field does not update automatically.
However, when using leancloud as storage, an API call error will occur because the updatedAt field is used as a …

修复使用leancloud存储时无法更新浏览量统计的问题 || Fixed the problem that page views statistics cannot be updated when using leancloud storage

---

packages/server/src/service/storage/leancloud.js

上个 #2113 合并更改遗忘错误
#2113 #2114 #2108 #1886 
---
Previous #2113 Merge changes forgotten error
#2113 #2114 #2108 #1886

Fix: * chore: use for...in replace hasOwnProperty

---

packages/server/src/service/notify.js

若按照教學（[連結](https://waline.js.org/en/guide/features/notification.html#discord-notification)）使用 Discord Webhook, 當輸入評論時，視窗會跳出錯誤訊息 `Unexpected end of JSON input`。
經查詢後，應該是 `waline/packages/server/src/service/notify.js` 中，fetch 回傳的 `resp` 中，body 是空的。
```
return fetch(DISCORD_WEBHOOK, {
method: 'POST',
header: form.getHeaders(),
body: form,
}).then((resp) => resp.json());
```
若將 `(resp) => resp.json()` 改為 `(resp) => resp.text()`, 則回傳結果為 `''`
因此，當使用 `resp.json()` 時，報錯 `Unexpected end of JSON input`，推測應該是因為傳入的內容為空字串。
經查詢後，回傳結果將會丟到變數 `discord` 中，並作為判斷是否要寄信的機制。
```
if (
[wechat, qq, telegram, qywxAmWechat, pushplus, discord, lark].every(
think.isEmpty,
)
) {
mailList.push({ to: AUTHOR, title, content });
}
```
因此，判斷 `discord` 中，只要有內容即可。
將 `(resp) => resp.json()` 修改為 `(resp) => …

fix: a minor change for fixing the warning causing from notifying by discord webhook

---

docs/src/guide/deploy/vps.md

文档中提供的 docker compose，即
```yaml
version: '3'
services:
waline:
container_name: waline
image: lizheming/waline:latest
restart: always
ports:
- 127.0.0.1:8360:8360
volumes:
- ${PWD}/data:/app/data
environment:
TZ: 'Asia/Shanghai'
SQLITE_PATH: '/app/data'
JWT_TOKEN: 'Your token'
SITE_NAME: 'Your site name'
SITE_URL: 'https://example.com'
SECURE_DOMAINS: 'example.com'
AUTHOR_EMAIL: 'mail@example.com'
```
中的 ports 字段有问题，如果在本地部署，则无法从局域网中访问（实测），因此可以删除 127.0.0.1 前缀
---
The docker compose provided in the documentation is
```yaml
version: '3'
services:
waline:
container_name:waline
image: lizheming/waline:latest
restart: always
ports:
- 127.0.0.1:8360:8360
volumes:
- ${PWD}/data:/app/data
environment:
TZ: 'Asia/Shanghai'
SQLITE_PATH: '/app/data'
JWT_TOKEN: 'Your token'
SITE_NAME: 'Your site name' …
```

更新文档独立部署的 docker compose || Update the document for independent deployment of docker compose

---

packages/api/src/articleCounter.ts
packages/api/src/pageview.ts
packages/client/src/pageview.ts
packages/server/src/controller/article.js

[fix] pageview api struct refactor

---

packages/server/src/service/notify.js

修复 mail 字段为 undefined 时的报错：
```
May 11 23:49:35 admired-nodes-1.localdomain node[160164]: TypeError: Cannot read property 'toLowerCase' of undefined
May 11 23:49:35 admired-nodes-1.localdomain node[160164]:     at module.exports.run (/root/waline/node_modules/@waline/vercel/src/service/notify.js:88:67)
May 11 23:49:35 admired-nodes-1.localdomain node[160164]:     at module.exports.postAction (/root/waline/node_modules/@waline/vercel/src/controller/comment.js:203:20)
May 11 23:49:35 admired-nodes-1.localdomain node[160164]:     at cors (/root/waline/node_modules/@koa/cors/index.js:110:16)
```

fix(server): #2502 , mail property undefined

---

packages/api/src/typings.ts

`reply_user` is being used in [CommentCard.vue](https://github.com/walinejs/waline/blob/100332388ef704466d59174e0fc354962ef132b8/packages/client/src/components/CommentCard.vue#L192) but not included in types.
See also: https://github.com/walinejs/waline/blob/100332388ef704466d59174e0fc354962ef132b8/packages/server/src/controller/comment.js#L583-L588

feat: add reply_user to WalineChildComment

---

packages/client/src/styles/helpers/_svg.scss

- Replace str-index with string.index
- Replace str-slice with string.slice
- Replace str-length with string.length
These changes address deprecation warnings from Dart Sass 3.0.0

fix(client): update sass functions to use new module syntax

---

docs/src/guide/features/notification.md
packages/server/src/service/notify.js

如果使用 Vercel 作为服务端，企业微信应用的可信 IP 就难以稳定设置（自部署在公网服务器的则不会碰到这种情况），因此目前常见的策略是使用一台公网 IP 服务器作为企业微信 API 的反向代理，并需要将此代理服务器添加到可信 IP.
Refs: #2753 #2661
以下是新引入的两个环境变量的简明文档：
[QYWX_PROXY]
用途: 指定企业微信接口的反向代理服务器地址（可信IP），未配置则不使用代理。
示例: 123.213.132.231
说明: 当设置此变量时，所有对企业微信 API 的请求将通过该代理服务器进行转发。
[QYWX_PROXY_PORT]
用途: 指定企业微信接口的反向代理服务器端口（默认 80）
示例: 8080
说明: 如果 [QYWX_PROXY] 设置了但未指定端口号，则使用此变量指定的端口号。如果未设置此变量，则默认使用 80 端口。
---
If Vercel is used as the server, the trusted IP of the enterprise WeChat application will be difficult to stably set (this situation will not happen if it is self-deployed on a public network server). Therefore, the current common strategy is to use a public network IP server as Reverse proxy for Enterprise WeChat API and need to add this proxy server to the trusted IP.
Refs: #2753 #2661
The …

feat(notify): support qywx api proxy

---

assets/waline.sql

1. **`wl_Comment` Table**:
- `idx_comment_url`: Speeds up filtering comments by `url`.
- `idx_comment_user_id`: Improves queries filtering by `user_id`.
- `idx_comment_status`: Useful for filtering by `status` (e.g., fetching only "approved" comments).
- `idx_comment_pid_rid`: Helps when fetching replies using `pid` and `rid`.
- `idx_comment_created_at` and `idx_comment_updated_at`: Useful for ordering or filtering based on date ranges.
- `idx_comment_sticky`: Optimizes filtering by `sticky` flag.
2. **`wl_Counter` Table**:
- `idx_counter_url`: Useful when counting reactions for specific URLs.
- `idx_counter_time`: Helps optimize time-based queries.
- `idx_counter_created_at`: Useful for sorting or filtering by creation date.
3. **`wl_Users` Table**:
- `idx_user_email`: A unique index on …

Add Indexes to Waline SQL table

---

packages/server/package.json

在 #2802 中，对 waline 企业微信推送的功能进行了 vercel server 条件下的修补完善（支持填入反向代理），此 PR 以便于维护者决定是否需要根据此改动发布新的 patch 版本，使得在生产环境中生效。因为上一次版本发布距今已有数月，固此改动未并入上一个 #2802 .
---
In #2802, the function of waline enterprise WeChat push has been patched and improved under vercel server conditions (supports filling in reverse proxy). This PR allows the maintainer to decide whether to release a new patch version based on this change, so that in Effective in production environment. Because it has been several months since the last version was released, this change has not been incorporated into the previous #2802.

chore: bump patched version enabling #2802

---

docs/src/en/reference/server/plugin.md
docs/src/reference/server/plugin.md

Add below plugins to support waline notification:
1. waline-notification-bark
2. waline-notification-telegram-bot
3. waline-notification-wecom-group-bot
4. waline-notification-lark-group-bot
5. waline-notification-slack-app

docs: add several notification plugins

---

packages/client/src/styles/panel.scss

- Added box-sizing: border-box to fix container overflow issues
- Ensures padding and border are included in element's total width/height calculation

fix: prevent child element overflow by adding box-sizing: border-box

---

packages/admin/src/pages/profile/index.jsx

This pr ensures that the corrected url and document remain consistent without affecting functionality
`http://127.0.0.1:8360/api/oauth/`->`http://127.0.0.1:8360/api/oauth`

fix(admin): the api path is the same as in the documentation

---

assets/waline.sql

我自建 [MySQL](https://waline.js.org/guide/database.html#mysql) 数据库时,根据指引导入 [wline.sql](https://github.com/walinejs/waline/blob/main/assets/waline.sql) 文件后出错:
```
[SQL] Query waline start
[ERR] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ADD INDEX `idx_comment_url` (`url`),
ADD INDEX `idx_comment_user_id` (`user_id' at line 23
[ERR] # Dump of table wl_Comment
CREATE TABLE `wl_Comment` (
`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
`user_id` int(11) DEFAULT NULL,
`comment` text,
`insertedAt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
`ip` varchar(100) DEFAULT '',
`link` varchar(255) DEFAULT NULL,
`mail` varchar(255) DEFAULT NULL,
`nick` varchar(255) DEFAULT NULL,
`pid` int(11) DEFAULT NULL, …
```

Fix waline.sql: A critical syntax error in the SQL file

---

example/vercel.json

起因是我发现用vercel一键部署的站点的**waline**评论系统的链接被搜索引擎索引了，单独的评论区前端页面不应该被索引的，看了一下链接发现没有`robots.txt`,但是看vercel控制台发现资源是有`robots.txt`文件的，应该是路由问题，改一下vercel配置就正常了
---
The reason is that I found that the link to the **waline** comment system of the site deployed with vercel is indexed by search engines. The front-end page of the separate comment area should not be indexed. After looking at the link, I found that there is no `robots.txt`, but looking at the vercel console, I found that the resource has `robots.txt` file, which should be a routing problem. It will be normal to change the vercel configuration.

fix: route to robots.txt
